# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adder.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='adder.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x61\x64\x64\x65r.proto\"\x1e\n\rAddOneRequest\x12\r\n\x05value\x18\x01 \x01(\x03\"\x1f\n\x0e\x41\x64\x64OneResponse\x12\r\n\x05value\x18\x01 \x01(\x03\x32\x34\n\x05\x41\x64\x64\x65r\x12+\n\x06\x41\x64\x64One\x12\x0e.AddOneRequest\x1a\x0f.AddOneResponse\"\x00\x62\x06proto3'
)




_ADDONEREQUEST = _descriptor.Descriptor(
  name='AddOneRequest',
  full_name='AddOneRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='AddOneRequest.value', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=45,
)


_ADDONERESPONSE = _descriptor.Descriptor(
  name='AddOneResponse',
  full_name='AddOneResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='AddOneResponse.value', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['AddOneRequest'] = _ADDONEREQUEST
DESCRIPTOR.message_types_by_name['AddOneResponse'] = _ADDONERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddOneRequest = _reflection.GeneratedProtocolMessageType('AddOneRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDONEREQUEST,
  '__module__' : 'adder_pb2'
  # @@protoc_insertion_point(class_scope:AddOneRequest)
  })
_sym_db.RegisterMessage(AddOneRequest)

AddOneResponse = _reflection.GeneratedProtocolMessageType('AddOneResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDONERESPONSE,
  '__module__' : 'adder_pb2'
  # @@protoc_insertion_point(class_scope:AddOneResponse)
  })
_sym_db.RegisterMessage(AddOneResponse)



_ADDER = _descriptor.ServiceDescriptor(
  name='Adder',
  full_name='Adder',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=80,
  serialized_end=132,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddOne',
    full_name='Adder.AddOne',
    index=0,
    containing_service=None,
    input_type=_ADDONEREQUEST,
    output_type=_ADDONERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADDER)

DESCRIPTOR.services_by_name['Adder'] = _ADDER

# @@protoc_insertion_point(module_scope)
